import 'package:flutter/material.dart';

enum TownPlay {
  tickle,
  deliver,
  catchToy,
  feed,
  stretch,
  bounce,
  decorate,
  scrub,
  inflate,
  grow,
  music,
  drive,
  tuck,
}

class TownDistrict {
  const TownDistrict(this.name, this.english, this.color, this.sky, this.dark);
  final String name, english;
  final Color color, sky, dark;
}

const townDistricts = [
  TownDistrict(
    '早安街道',
    'GOOD MORNING',
    Color(0xFFF6C65D),
    Color(0xFFFFF3D9),
    Color(0xFF947129),
  ),
  TownDistrict(
    '怪味厨房',
    'YUMMY YUMMY',
    Color(0xFFF3A28A),
    Color(0xFFFFEDE2),
    Color(0xFFA45640),
  ),
  TownDistrict(
    '泡泡澡堂',
    'BUBBLE TIME',
    Color(0xFF83C9CE),
    Color(0xFFE4F4F1),
    Color(0xFF367D83),
  ),
  TownDistrict(
    '神奇花园',
    'LITTLE GARDEN',
    Color(0xFFA9C992),
    Color(0xFFEDF3DF),
    Color(0xFF587B46),
  ),
  TownDistrict(
    '咕噜车站',
    'LET’S GO',
    Color(0xFF90B9D5),
    Color(0xFFE7EFF6),
    Color(0xFF476F91),
  ),
  TownDistrict(
    '睡衣乐园',
    'TWINKLE TOWN',
    Color(0xFFB7A5D6),
    Color(0xFFEEEAFA),
    Color(0xFF76618E),
  ),
];

class TownLevel {
  const TownLevel(
    this.id,
    this.title,
    this.instruction,
    this.play,
    this.subject,
    this.props,
    this.words,
    this.meanings,
    this.phrase,
    this.translation,
    this.surprise,
  );
  final int id;
  final String title, instruction, subject, phrase, translation, surprise;
  final TownPlay play;
  final List<String> props, words, meanings;
  int get district => id ~/ 5;
  int get number => id + 1;
  TownDistrict get area => townDistricts[district];
  int get goal => switch (play) {
    TownPlay.tickle || TownPlay.stretch || TownPlay.inflate => 8,
    TownPlay.scrub ||
    TownPlay.catchToy ||
    TownPlay.bounce ||
    TownPlay.music ||
    TownPlay.drive => 6,
    _ => 3,
  };
}

// Concrete object → action → short phrase. Each group repeats familiar language
// in a new setting; nothing depends on reading, spelling, or a correct accent.
const townLevels = <TownLevel>[
  TownLevel(
    0,
    '给太阳挠痒痒',
    '摸摸太阳的小肚子，把它笑醒吧！',
    TownPlay.tickle,
    'sun',
    ['feather', 'cloud', 'flower'],
    ['Sun', 'Tickle', 'Happy'],
    ['太阳', '挠痒痒', '开心'],
    'Wake up, sunshine!',
    '太阳，起床啦！',
    '阿嚏！太阳喷出了一道彩虹',
  ),
  TownLevel(
    1,
    '房子也要穿鞋',
    '把小鞋子拖给房子，它想出去散步。',
    TownPlay.deliver,
    'house',
    ['shoe', 'shoe', 'hat'],
    ['Shoes', 'Feet', 'Walk'],
    ['鞋子', '小脚', '走一走'],
    'Let’s go for a walk!',
    '我们去散步吧！',
    '小房子穿上鞋，踢踢踏踏去散步',
  ),
  TownLevel(
    2,
    '云朵打喷嚏',
    '轻轻挠一挠云朵，它的鼻子好痒呀。',
    TownPlay.tickle,
    'cloud',
    ['feather', 'cloud', 'star'],
    ['Cloud', 'Soft', 'Sneeze'],
    ['云朵', '软软的', '打喷嚏'],
    'Achoo! Excuse me!',
    '阿嚏！不好意思！',
    '云朵的喷嚏变成了棉花糖雨',
  ),
  TownLevel(
    3,
    '袜子逃跑啦',
    '点点跳来跳去的袜子，把它们叫回来。',
    TownPlay.catchToy,
    'monster',
    ['sock', 'sock', 'sock'],
    ['Sock', 'Catch', 'Come back'],
    ['袜子', '抓住啦', '回来呀'],
    'Come back, little socks!',
    '小袜子，快回来！',
    '袜子排成队，跳起了踢踏舞',
  ),
  TownLevel(
    4,
    '全小镇早操',
    '点点小鼓，带朋友们一起动一动。',
    TownPlay.music,
    'monster',
    ['drum', 'bell', 'star'],
    ['Clap', 'Jump', 'Dance'],
    ['拍拍手', '跳一跳', '跳舞'],
    'Clap, clap! Jump, jump!',
    '拍拍手，跳一跳！',
    '房子、树和小怪兽一起摇摆',
  ),
  TownLevel(
    5,
    '变声水果餐',
    '把水果喂给啵啵，听听它的新声音。',
    TownPlay.feed,
    'monster',
    ['apple', 'banana', 'berry'],
    ['Apple', 'Banana', 'Strawberry'],
    ['苹果', '香蕉', '草莓'],
    'Yummy! I love fruit!',
    '好吃！我喜欢水果！',
    '水果变成了啵啵的彩虹头发',
  ),
  TownLevel(
    6,
    '一根长长面',
    '拉一拉面条，也可以轻点让它变长。',
    TownPlay.stretch,
    'bowl',
    ['noodle', 'fork', 'star'],
    ['Long', 'Pull', 'Noodles'],
    ['长长的', '拉一拉', '面条'],
    'So long! Slurp, slurp!',
    '好长呀！吸溜吸溜！',
    '面条弹回来，变成卷卷胡子',
  ),
  TownLevel(
    7,
    '蹦蹦吐司',
    '点一点吐司，让它从烤面包机里跳出来。',
    TownPlay.bounce,
    'toaster',
    ['toast', 'toast', 'toast'],
    ['Toast', 'Up', 'Down'],
    ['吐司', '上面', '下面'],
    'Up and down! Pop!',
    '上上下下，蹦！',
    '吐司长出小翅膀，在天上翻跟头',
  ),
  TownLevel(
    8,
    '布丁扭屁股',
    '把小装饰放到布丁身上，变得漂漂亮亮。',
    TownPlay.decorate,
    'pudding',
    ['berry', 'star', 'cherry'],
    ['Pink', 'Yellow', 'Red'],
    ['粉色', '黄色', '红色'],
    'Wiggle, wiggle, jelly!',
    '扭一扭，小布丁！',
    '布丁戴着水果帽子跳摇摆舞',
  ),
  TownLevel(
    9,
    '蛋糕小火车',
    '把小蛋糕拖到车厢上，甜甜火车要出发啦。',
    TownPlay.deliver,
    'train',
    ['cake', 'cake', 'cake'],
    ['Cake', 'Sweet', 'Train'],
    ['蛋糕', '甜甜的', '火车'],
    'All aboard! Choo choo!',
    '上车啦！呜呜！',
    '小火车喷出一串奶油云朵',
  ),
  TownLevel(
    10,
    '泥巴怪洗澡',
    '擦一擦小泥点，帮啵啵洗个香香澡。',
    TownPlay.scrub,
    'monster',
    ['sponge', 'drop', 'bubble'],
    ['Wash', 'Clean', 'Splash'],
    ['洗一洗', '干净啦', '哗啦'],
    'Wash, wash! All clean!',
    '洗一洗，干净啦！',
    '泥点洗掉后，露出了彩虹肚皮',
  ),
  TownLevel(
    11,
    '泡泡大胡子',
    '按住小怪兽吹泡泡，松开看看大胡子。',
    TownPlay.inflate,
    'monster',
    ['bubble', 'bubble', 'bubble'],
    ['Bubble', 'Big', 'Pop'],
    ['泡泡', '大大的', '啵！'],
    'A big bubble! Pop!',
    '一个大泡泡！啵！',
    '泡泡变成大胡子，然后一个个啵啵爆开',
  ),
  TownLevel(
    12,
    '小鸭捉迷藏',
    '点点水里的小鸭，带它们排队游泳。',
    TownPlay.catchToy,
    'duck',
    ['duck', 'duck', 'duck'],
    ['Duck', 'Yellow', 'Quack'],
    ['小鸭', '黄色', '嘎嘎'],
    'Hello, little duck!',
    '你好呀，小鸭！',
    '六只小鸭摇摇摆摆游成一颗爱心',
  ),
  TownLevel(
    13,
    '水管打嗝啦',
    '把弯弯水管拖过来，帮水滴找到出口。',
    TownPlay.deliver,
    'pipe',
    ['pipe', 'pipe', 'pipe'],
    ['Water', 'Turn', 'Flow'],
    ['水', '转一转', '流起来'],
    'Here comes the water!',
    '水流出来啦！',
    '水管打个嗝，喷出了彩虹喷泉',
  ),
  TownLevel(
    14,
    '坐泡泡飞起来',
    '按住啵啵吹大泡泡，带它轻轻飞起来。',
    TownPlay.inflate,
    'monster',
    ['bubble', 'cloud', 'star'],
    ['Small', 'Big', 'Fly'],
    ['小小的', '大大的', '飞起来'],
    'Up, up and away!',
    '飞呀飞，飞起来！',
    '啵啵坐上透明泡泡，向云朵挥挥手',
  ),
  TownLevel(
    15,
    '种一朵哈哈花',
    '把小水滴拖给花苗，看看会长出什么。',
    TownPlay.grow,
    'flower',
    ['drop', 'drop', 'drop'],
    ['Seed', 'Water', 'Flower'],
    ['种子', '浇水', '花朵'],
    'Grow, little flower!',
    '小花，快快长！',
    '小花长出笑脸，咯咯笑个不停',
  ),
  TownLevel(
    16,
    '蜗牛换新家',
    '给蜗牛送来漂亮的小房子。',
    TownPlay.decorate,
    'snail',
    ['shell', 'flower', 'star'],
    ['Home', 'Round', 'Snail'],
    ['家', '圆圆的', '蜗牛'],
    'Home sweet home!',
    '温暖的小家！',
    '蜗牛背上会旋转的彩色小房子',
  ),
  TownLevel(
    17,
    '毛毛虫穿袜子',
    '把袜子拖给毛毛虫，帮它的小脚暖起来。',
    TownPlay.deliver,
    'caterpillar',
    ['sock', 'sock', 'sock'],
    ['One', 'Two', 'Three'],
    ['一', '二', '三'],
    'One, two, three! Happy feet!',
    '一二三，小脚真开心！',
    '毛毛虫用六只脚跳起滑稽舞',
  ),
  TownLevel(
    18,
    '蘑菇小乐队',
    '点点三个蘑菇，每个都有自己的声音。',
    TownPlay.music,
    'mushroom',
    ['mushroom', 'mushroom', 'mushroom'],
    ['Tap', 'Listen', 'Music'],
    ['点一点', '听一听', '音乐'],
    'Tap, tap! Make music!',
    '点一点，一起奏乐！',
    '蘑菇亮起小灯，瓢虫也来伴舞',
  ),
  TownLevel(
    19,
    '大树伸懒腰',
    '给大树挠痒痒，叫醒它的叶子。',
    TownPlay.tickle,
    'tree',
    ['leaf', 'feather', 'flower'],
    ['Tree', 'Green', 'Stretch'],
    ['树', '绿色', '伸懒腰'],
    'Hello, big green tree!',
    '你好，绿色的大树！',
    '大树伸个懒腰，树叶变成小蝴蝶',
  ),
  TownLevel(
    20,
    '水果轮子车',
    '给小汽车装上水果轮子，看看它怎么开。',
    TownPlay.deliver,
    'car',
    ['orange', 'melon', 'apple'],
    ['Orange', 'Round', 'Wheel'],
    ['橙子', '圆圆的', '轮子'],
    'Round and round we go!',
    '圆圆轮子转呀转！',
    '水果轮子挤出果汁，路边花朵唱起歌',
  ),
  TownLevel(
    21,
    '公交车怕痒痒',
    '挠挠公交车的肚子，逗它笑一笑。',
    TownPlay.tickle,
    'bus',
    ['feather', 'star', 'cloud'],
    ['Bus', 'Tickle', 'Laugh'],
    ['公交车', '挠痒痒', '哈哈笑'],
    'Ha ha! That tickles!',
    '哈哈！好痒呀！',
    '公交车笑得蹦起来，车窗变成笑脸',
  ),
  TownLevel(
    22,
    '动物上火车',
    '把小动物送上车，一起去旅行。',
    TownPlay.deliver,
    'train',
    ['cat', 'duck', 'frog'],
    ['Cat', 'Duck', 'Frog'],
    ['小猫', '小鸭', '青蛙'],
    'Let’s ride the train!',
    '我们一起坐火车！',
    '每节车厢都唱出了动物的声音',
  ),
  TownLevel(
    23,
    '月亮的软枕头',
    '把枕头、星星和小被子送给月亮。',
    TownPlay.tuck,
    'moon',
    ['pillow', 'star', 'blanket'],
    ['Moon', 'Pillow', 'Soft'],
    ['月亮', '枕头', '软软的'],
    'Good night, little moon!',
    '晚安，小月亮！',
    '月亮盖上被子，呼噜变成了小星星',
  ),
  TownLevel(
    24,
    '小象消防车',
    '点点小车，开去给口渴的小花浇水。',
    TownPlay.drive,
    'elephant',
    ['drop', 'flower', 'bell'],
    ['Go', 'Stop', 'Water'],
    ['出发', '停一停', '浇水'],
    'Let’s water the flowers!',
    '一起给小花浇水！',
    '小象用鼻子喷出一道爱心喷泉',
  ),
  TownLevel(
    25,
    '气球变鬼脸',
    '把眼睛、嘴巴和小帽子送给气球。',
    TownPlay.decorate,
    'balloon',
    ['eyes', 'smile', 'hat'],
    ['Eyes', 'Mouth', 'Funny'],
    ['眼睛', '嘴巴', '好滑稽'],
    'What a funny face!',
    '好滑稽的一张脸！',
    '气球做个鬼脸，带着小帽子飞起来',
  ),
  TownLevel(
    26,
    '果冻蹦蹦床',
    '点点啵啵，陪它在果冻上蹦一蹦。',
    TownPlay.bounce,
    'pudding',
    ['star', 'bubble', 'heart'],
    ['Jump', 'High', 'Bounce'],
    ['跳一跳', '高高的', '弹起来'],
    'Jump up high!',
    '跳得高高的！',
    '果冻弹出小星星，啵啵翻了一个跟头',
  ),
  TownLevel(
    27,
    '旋转动物园',
    '点点小动物，让它们坐上旋转木马。',
    TownPlay.music,
    'carousel',
    ['cat', 'duck', 'frog'],
    ['Slow', 'Fast', 'Round'],
    ['慢慢的', '快快的', '转一圈'],
    'Round and round!',
    '转呀转，转一圈！',
    '小动物们边旋转边轮流打招呼',
  ),
  TownLevel(
    28,
    '星星找被窝',
    '把软软的小被子拖给星星，它想睡觉啦。',
    TownPlay.tuck,
    'star',
    ['pillow', 'blanket', 'heart'],
    ['Star', 'Sleep', 'Night'],
    ['星星', '睡觉', '夜晚'],
    'Twinkle, twinkle, little star.',
    '一闪一闪，小星星。',
    '星星慢慢闭上眼睛，天空亮起小夜灯',
  ),
  TownLevel(
    29,
    '晚安睡衣派对',
    '点点乐器，和所有朋友跳最后一支舞。',
    TownPlay.music,
    'party',
    ['drum', 'bell', 'star'],
    ['Hello', 'Friends', 'Good night'],
    ['你好', '朋友们', '晚安'],
    'Good night, my friends!',
    '晚安，我的朋友们！',
    '大家穿着睡衣挥挥手，明天再一起玩',
  ),
];
