import 'package:flutter/material.dart';

enum DressCategory { outfit, top, bottom, shoes, hair, accessory }

extension DressCategoryInfo on DressCategory {
  String get label => const ['套装', '上衣', '下装', '鞋子', '头发', '配饰'][index];
  IconData get icon => const [
    Icons.checkroom_rounded,
    Icons.dry_cleaning_rounded,
    Icons.accessibility_new_rounded,
    Icons.ice_skating_rounded,
    Icons.face_3_rounded,
    Icons.auto_awesome_rounded,
  ][index];
}

@immutable
class DressItem {
  const DressItem(
    this.id,
    this.name,
    this.category,
    this.color,
    this.accent,
    this.shape,
  );
  final String id, name, shape;
  final DressCategory category;
  final Color color, accent;
}

const dressCatalog = <DressItem>[
  DressItem(
    'petal',
    '花瓣小裙',
    DressCategory.outfit,
    Color(0xFFE7A6B1),
    Color(0xFFFFE7CC),
    'dress',
  ),
  DressItem(
    'pinafore',
    '花园背带裙',
    DressCategory.outfit,
    Color(0xFF95ADA0),
    Color(0xFFFFEAD2),
    'pinafore',
  ),
  DressItem(
    'starlight',
    '星光纱裙',
    DressCategory.outfit,
    Color(0xFFAAA5CC),
    Color(0xFFFCE5A7),
    'tutu',
  ),
  DressItem(
    'raincoat',
    '柠檬小雨衣',
    DressCategory.outfit,
    Color(0xFFF3CA69),
    Color(0xFFFFF3D5),
    'coat',
  ),
  DressItem(
    'sleepy',
    '云朵睡衣',
    DressCategory.outfit,
    Color(0xFF9BBFD0),
    Color(0xFFF5EBDD),
    'pajamas',
  ),
  DressItem(
    'explorer',
    '森林探险家',
    DressCategory.outfit,
    Color(0xFFC5B292),
    Color(0xFF748E76),
    'safari',
  ),
  DressItem(
    'tee',
    '海风条纹',
    DressCategory.top,
    Color(0xFF9DBDC5),
    Color(0xFFFFF1DB),
    'stripe',
  ),
  DressItem(
    'cardigan',
    '草莓开衫',
    DressCategory.top,
    Color(0xFFDFA4A1),
    Color(0xFFFFEAD6),
    'cardigan',
  ),
  DressItem(
    'blouse',
    '小花衬衣',
    DressCategory.top,
    Color(0xFFF0DBB6),
    Color(0xFFD9A094),
    'blouse',
  ),
  DressItem(
    'knit',
    '薄荷毛衣',
    DressCategory.top,
    Color(0xFF98B5A3),
    Color(0xFFECDEC8),
    'knit',
  ),
  DressItem(
    'hoodie',
    '蓝莓卫衣',
    DressCategory.top,
    Color(0xFFA4A3C6),
    Color(0xFFE9DCF3),
    'hoodie',
  ),
  DressItem(
    'sailor',
    '水手领上衣',
    DressCategory.top,
    Color(0xFFEFDFC8),
    Color(0xFF7297AB),
    'sailor',
  ),
  DressItem(
    'shorts',
    '奶油短裤',
    DressCategory.bottom,
    Color(0xFFD5B893),
    Color(0xFFFAE6C4),
    'shorts',
  ),
  DressItem(
    'pleats',
    '桃子百褶裙',
    DressCategory.bottom,
    Color(0xFFD9A19B),
    Color(0xFFF4C7B5),
    'pleats',
  ),
  DressItem(
    'jeans',
    '天空牛仔裤',
    DressCategory.bottom,
    Color(0xFF88A8B9),
    Color(0xFFCCDCE0),
    'pants',
  ),
  DressItem(
    'bloomers',
    '小南瓜裤',
    DressCategory.bottom,
    Color(0xFFDCB569),
    Color(0xFFF8E1AD),
    'bloomers',
  ),
  DressItem(
    'cloudskirt',
    '云朵蓬蓬裙',
    DressCategory.bottom,
    Color(0xFFC0B5CD),
    Color(0xFFF3E5EF),
    'tutu',
  ),
  DressItem(
    'dungarees',
    '小熊背带裤',
    DressCategory.bottom,
    Color(0xFF9AAF96),
    Color(0xFFF0DCBC),
    'dungarees',
  ),
  DressItem(
    'maryjane',
    '莓果小皮鞋',
    DressCategory.shoes,
    Color(0xFFAD686F),
    Color(0xFFEFD8B6),
    'maryjane',
  ),
  DressItem(
    'wellies',
    '小黄雨靴',
    DressCategory.shoes,
    Color(0xFFE8BD59),
    Color(0xFFFFE7AE),
    'boots',
  ),
  DressItem(
    'sneakers',
    '薄荷运动鞋',
    DressCategory.shoes,
    Color(0xFF91AFA5),
    Color(0xFFFFF0D7),
    'sneakers',
  ),
  DressItem(
    'ballet',
    '蜜桃芭蕾鞋',
    DressCategory.shoes,
    Color(0xFFDEAFA9),
    Color(0xFFFBE0D1),
    'ballet',
  ),
  DressItem(
    'bunny',
    '兔兔拖鞋',
    DressCategory.shoes,
    Color(0xFFE2CCBA),
    Color(0xFFE4ABAB),
    'bunny',
  ),
  DressItem(
    'hiking',
    '森林小靴',
    DressCategory.shoes,
    Color(0xFFAA886C),
    Color(0xFFDACAAC),
    'boots',
  ),
  DressItem(
    'bob',
    '软软短发',
    DressCategory.hair,
    Color(0xFF715044),
    Color(0xFFA67A5C),
    'bob',
  ),
  DressItem(
    'pigtails',
    '双双小辫',
    DressCategory.hair,
    Color(0xFF6C493C),
    Color(0xFFDB9D94),
    'pigtails',
  ),
  DressItem(
    'waves',
    '栗子卷发',
    DressCategory.hair,
    Color(0xFF8A6248),
    Color(0xFFB68C65),
    'waves',
  ),
  DressItem(
    'buns',
    '丸子头',
    DressCategory.hair,
    Color(0xFF493A38),
    Color(0xFFB9988E),
    'buns',
  ),
  DressItem(
    'braids',
    '编编麻花辫',
    DressCategory.hair,
    Color(0xFF956F48),
    Color(0xFFCAAA78),
    'braids',
  ),
  DressItem(
    'pixie',
    '俏皮小短发',
    DressCategory.hair,
    Color(0xFF503D35),
    Color(0xFF92705A),
    'pixie',
  ),
  DressItem(
    'bow',
    '蝴蝶结',
    DressCategory.accessory,
    Color(0xFFD58F97),
    Color(0xFFF8D8C8),
    'bow',
  ),
  DressItem(
    'flower',
    '雏菊花环',
    DressCategory.accessory,
    Color(0xFFF4E2BB),
    Color(0xFFE7BD60),
    'flower',
  ),
  DressItem(
    'beret',
    '画家小帽',
    DressCategory.accessory,
    Color(0xFFBC9982),
    Color(0xFFE2C4A4),
    'beret',
  ),
  DressItem(
    'crown',
    '星星王冠',
    DressCategory.accessory,
    Color(0xFFE0BA6B),
    Color(0xFFFFF0BE),
    'crown',
  ),
  DressItem(
    'bunnyears',
    '兔耳发箍',
    DressCategory.accessory,
    Color(0xFFEBD8C2),
    Color(0xFFD7A7A5),
    'ears',
  ),
  DressItem(
    'satchel',
    '小花挎包',
    DressCategory.accessory,
    Color(0xFFAA7E62),
    Color(0xFFEEC68A),
    'bag',
  ),
];

final dressItemsById = {for (final item in dressCatalog) item.id: item};

enum DressPlace { studio, garden, tea, night }

extension DressPlaceInfo on DressPlace {
  String get label => const ['衣帽间', '雨天花园', '点心茶会', '星空睡前'][index];
  String get invitation =>
      const ['挑一件喜欢的衣服吧', '一起踩踩小水坑', '给小兔倒一杯花茶', '把星星轻轻点亮'][index];
  String get action => const ['摇一摇', '踩水坑', '倒花茶', '点星星'][index];
  IconData get icon => const [
    Icons.home_rounded,
    Icons.water_drop_rounded,
    Icons.local_cafe_rounded,
    Icons.nightlight_round,
  ][index];
  Color get color => const [
    Color(0xFFD5B898),
    Color(0xFF94AFA6),
    Color(0xFFDCA59C),
    Color(0xFFA5A2C7),
  ][index];
}
